Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine319"
  config.vm.hostname = "alimpensS"
  # Second NIC = private network (eth1)
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 1
  end

  config.vm.synced_folder "../", "/vagrant"
  config.vm.provision "shell", path: "server.sh"
end
