#!/usr/bin/env bash

VAGRANT_DIR='infra/'
APP_IP='192.168.56.110'
APP_DOMAINS=("app1.com" "app2.com" "app3.com")

cd "$VAGRANT_DIR"

if ! grep -q 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' ~/.bashrc; then
  echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.bashrc
fi

if ! grep -q 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' ~/.zshrc; then
  echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.zshrc
fi
sudo chmod 644 /etc/rancher/k3s/k3s.yaml

echo "Starting p2 ..."
echo -e "\033[1;34m[INFO] Checking VirtualBox version...\033[0m"
vboxmanage --version || echo "VirtualBox not found!"

echo -e "\033[1;34m[INFO] Checking Vagrant version...\033[0m"
vagrant --version || echo "Vagrant not found!"

echo -e "\033[1;33m[INFO] Removing KVM modules (requires sudo)...\033[0m"
sudo rmmod kvm_intel || true
sudo rmmod kvm || true

echo -e "\033[1;32m[INFO] Starting Vagrant...\033[0m"
vagrant up

echo "Ensuring /etc/hosts contains entry for $APP_DOMAIN..."
for domain in "${APP_DOMAINS[@]}"; do
    if ! grep -q "$domain" /etc/hosts; then
        echo "$APP_IP $domain" | sudo tee -a /etc/hosts > /dev/null
        echo "[INFO] Added $domain to /etc/hosts"
    else
        echo "[INFO] $domain already exists in /etc/hosts"
    fi
done

echo "Deploying ALL apps (app1, app2)..."

echo "Deploying app1 (external image)..."
vagrant ssh -c "kubectl apply -f /vagrant/apps/app1/k8s"
echo "Deploying app2 (external image)..."
vagrant ssh -c "kubectl apply -f /vagrant/apps/app2/k8s"
echo "Deploying app3 (external image)..."
vagrant ssh -c "kubectl apply -f /vagrant/apps/app3/k8s"

echo "Applying global Ingress..."
vagrant ssh -c "sudo kubectl apply -f /vagrant/infra/k8s/ingress.yaml"

